[AutoProxy 0.2.9]
||cloudflare.com
||ytimg.com
||youtube.com
||doubleclick.net
||googlevideo.com
||instagram.com
||ggpht.com
||3proxy.ru
||digitalocean.com
||jetbrains.com
||myjetbrains.com
||jb.gg
||cloudfront.net
||inertiajs.com
||xerox.com
||timeweb.cloud
||romslab.com
||wikitide.net
||fortheusers.org
||rutracker.cc
||arm.com
||b-cdn.net
||iterm2.com
||jibbsmart.com
||gyrowiki.jibbsmart.com
